dist: trusty
sudo: required
language: node_js

node_js:
  - "6.5.0"

env:
  global:
    - CHROME_BIN=chromium-browser
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser

before_script:
  - sh -e /etc/init.d/xvfb start

os:
  - linux

install:
  - npm install

script:
  - npm run lint
  - npm run tsc
  - npm run test-once
