language: node_js
sudo: false

node_js:
  - "6.5.0"

env:
  global:
    - CHROME_BIN=chromium-browser

os:
  - linux

install:
  - npm install

script:
  - npm run lint
  - npm run tsc
  - npm run test-once
